#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Execute DSelector
#
# example usage:
#
# ./DSelector/scripts/execute_DSelector
#



import sys, os, argparse
import numpy as np
#import pandas as pd
import matplotlib.pyplot as plt
import ROOT


parser = argparse.ArgumentParser(description='Execute DSelector')
parser.add_argument("--time", type=float,     default=1, required=False, help="Acquisition time (in seconds)")
args = parser.parse_args()

intervaltime= args.time

ROOT.gSystem.AddIncludePath("-I${HALLD_RECON_HOME}/${BMS_OSNAME}/include/");
ROOT.gSystem.AddIncludePath("-I${ROOT_ANALYSIS_HOME}/${BMS_OSNAME}/include/");
ROOT.gSystem.Load("$(ROOT_ANALYSIS_HOME)/$(BMS_OSNAME)/lib/libDSelector.so");


os.chdir("/w/hallb-scshelf2102/clas12/users/ecohen/halld/GlueX/GlueX_BranchingRatios_Analysis/DSelector/gamma_n_To_rhom_p_X")
#print(os.pwd())
inFileName = "../../../tree_gd_pi0pimprotinc__B4_F4_T2_S2_090206.root"
inFile = ROOT.TFile.Open(inFileName ,"READ")
inTree = inFile.Get("gd_pi0pimprotinc__B4_F4_T2_S2_Tree")
inTree.Process("DSelector_gamma_n_To_rhom_p_X.C+")
#inTree.Process("DSelector/First_DSelector/DSelector_Erez_First_DSelector.C+")

os.chdir("/w/hallb-scshelf2102/clas12/users/ecohen/halld/GlueX/GlueX_BranchingRatios_Analysis")

exit()


